<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StuffSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('stuffs')->insert([
            "user_id" => 1,
            "class_id" => 4,
            "is_private" => 1,
            "character_level" => 200,
            "gender" => "female",
            "title" => "stuff air",
            "is_exo_pa" => 1,
            "is_exo_pm" => 1,
            "is_exo_po" => 0,
            "vitality_boost" => 3,
            "intel_boost" => 0,
            "strength_boost" => 0,
            "luck_boost" => 0,
            "wisdom_boost" => 0,
            "agility_boost" => 398,
            "vitality_parchment" => 100,
            "intel_parchment" => 100,
            "strength_parchment" => 100,
            "luck_parchment" => 100,
            "wisdom_parchment" => 100,
            "agility_parchment" => 100,
            "amulet_id" => 17581,
            "shield_id" => 18700,
            "ring_1_id" => 13124,
            "belt_id" => 19599,
            "boots_id" => 13125,
            "hat_id" => 13123,
            "weapon_id" => 18014,
            "ring_2_id" => 17582,
            "cape_id" => 17583,
            "animal_id" => 177,
            "dofus_1_id" => 7043,
            "dofus_2_id" => 8698,
            "dofus_3_id" => 694,
            "dofus_4_id" => 12714,
            "dofus_5_id" => 13830,
            "dofus_6_id" => 13828,
            "total_vitality" => 3903,
            "total_prospection" => 215,
            "total_pa" => 12,
            "total_pm" => 6,
            "total_po" => 5,
            "total_initiative" => 1953,
            "subtotal_vitality" => 2853,
            "subtotal_intel" => 100,
            "subtotal_agility" => 1353,
            "subtotal_strength" => 100,
            "subtotal_luck" => 100,
            "subtotal_wisdom" => 445,
            "leak" => 129,
            "avoid_pa" => 75,
            "avoid_pm" => 85,
            "pods" => 1500,
            "tackle" => 120,
            "pa_recession" => 44,
            "pm_recession" => 44,
            "stuff_level" => 200,
            "stuff_vitality" => 2750,
            "stuff_strength" => 0,
            "stuff_intel" => 0,
            "stuff_luck" => 0,
            "stuff_agility" => 855,
            "stuff_wisdom" => 345,
            "stuff_initiative" => 300,
            "stuff_leak" => -6,
            "stuff_avoid_pm" => 41,
            "stuff_avoid_pa" => 31,
            "stuff_pa_recession" => 0,
            "stuff_pm_recession" => 0,
            "stuff_pods" => 0,
            "stuff_prospection" => 105,
            "stuff_tackle" => -15,
            "stuff_invocation" => 5,
            "stuff_health" => 0,
            "stuff_power" => 190,
            "stuff_critic" => -1,
            "stuff_pa" => 4,
            "stuff_pm" => 2,
            "stuff_po" => 5,
            "stuff_neutral_res" => 15,
            "stuff_luck_res" => 15,
            "stuff_strength_res" => 0,
            "stuff_intel_res" => 0,
            "stuff_agility_res" => 0,
            "stuff_percent_neutral_res" => 10,
            "stuff_percent_luck_res" => 37,
            "stuff_percent_strength_res" => 20,
            "stuff_percent_intel_res" => 10,
            "stuff_percent_agility_res" => 10,
            "stuff_distance_res" => 0,
            "stuff_critique_res" => 45,
            "stuff_push_res" => 55,
            "stuff_melee_res" => 0,
            "stuff_weapon_res" => 0,
            "stuff_do_neutral" => 25,
            "stuff_do_strength" => 25,
            "stuff_do_intel" => 25,
            "stuff_do_agility" => 178,
            "stuff_do_luck" => 25,
            "stuff_do_critique" => 12,
            "stuff_do_push" => 0,
            "stuff_do_melee" => -14,
            "stuff_do_distance" => 14,
            "stuff_do_weapon" => 0,
            "stuff_do_spell" => 0
        ]);
        DB::table('stuffs')->insert([
            "user_id" => 1,
            "class_id" => 5,
            "is_private" => 1,
            "character_level" => 200,
            "gender" => "female",
            "title" => "Xélor multi",
            "is_exo_pa" => 0,
            "is_exo_pm" => 0,
            "is_exo_po" => 0,
            "vitality_boost" => 35,
            "intel_boost" => 140,
            "strength_boost" => 140,
            "luck_boost" => 140,
            "wisdom_boost" => 0,
            "agility_boost" => 240,
            "vitality_parchment" => 100,
            "intel_parchment" => 100,
            "strength_parchment" => 100,
            "luck_parchment" => 100,
            "wisdom_parchment" => 100,
            "agility_parchment" => 100,
            "amulet_id" => 19984,
            "shield_id" => 19263,
            "ring_1_id" => 19985,
            "belt_id" => 19983,
            "boots_id" => 17578,
            "hat_id" => 17579,
            "weapon_id" => 19986,
            "ring_2_id" => 21223,
            "cape_id" => 17580,
            "animal_id" => 290,
            "dofus_1_id" => 694,
            "dofus_2_id" => 7043,
            "dofus_3_id" => 8698,
            "dofus_4_id" => 13830,
            "dofus_5_id" => 13834,
            "dofus_6_id" => 13828,
            "total_vitality" => 4035,
            "total_prospection" => 194,
            "total_pa" => 11,
            "total_pm" => 6,
            "total_po" => 3,
            "total_initiative" => 2560,
            "subtotal_vitality" => 2985,
            "subtotal_intel" => 640,
            "subtotal_agility" => 640,
            "subtotal_strength" => 640,
            "subtotal_luck" => 640,
            "subtotal_wisdom" => 315,
            "leak" => 51,
            "avoid_pa" => 31,
            "avoid_pm" => 51,
            "pods" => 4200,
            "tackle" => 34,
            "pa_recession" => 31,
            "pm_recession" => 31,
            "stuff_level" => 200,
            "stuff_vitality" => 2850,
            "stuff_strength" => 400,
            "stuff_intel" => 400,
            "stuff_luck" => 400,
            "stuff_agility" => 300,
            "stuff_wisdom" => 215,
            "stuff_initiative" => 0,
            "stuff_leak" => -13,
            "stuff_avoid_pm" => 20,
            "stuff_avoid_pa" => 0,
            "stuff_pa_recession" => 0,
            "stuff_pm_recession" => 0,
            "stuff_pods" => 0,
            "stuff_prospection" => 30,
            "stuff_tackle" => -30,
            "stuff_invocation" => 3,
            "stuff_health" => 0,
            "stuff_power" => 300,
            "stuff_critic" => 25,
            "stuff_pa" => 4,
            "stuff_pm" => 3,
            "stuff_po" => 3,
            "stuff_neutral_res" => 0,
            "stuff_luck_res" => 0,
            "stuff_strength_res" => 0,
            "stuff_intel_res" => 0,
            "stuff_agility_res" => 0,
            "stuff_percent_neutral_res" => 15,
            "stuff_percent_luck_res" => 20,
            "stuff_percent_strength_res" => 30,
            "stuff_percent_intel_res" => 26,
            "stuff_percent_agility_res" => 16,
            "stuff_distance_res" => 0,
            "stuff_critique_res" => 100,
            "stuff_push_res" => 20,
            "stuff_melee_res" => 0,
            "stuff_weapon_res" => 0,
            "stuff_do_neutral" => 117,
            "stuff_do_strength" => 117,
            "stuff_do_intel" => 117,
            "stuff_do_agility" => 97,
            "stuff_do_luck" => 117,
            "stuff_do_critique" => -9,
            "stuff_do_push" => 0,
            "stuff_do_melee" => 15,
            "stuff_do_distance" => 0,
            "stuff_do_weapon" => -15,
            "stuff_do_spell" => 0,

        ]);

    }
}
